### ISSUE TITLE
Sprint 3: 31 Jan - 4 Feb

### ISSUE THREAD

**Issue by backeb** [c-scale-community/use-case-aquamonitor#23]
Notes from sprint planning meeting can be found here: https://confluence.egi.eu/display/CSCALE/2022-01-20+Planning+the+next+Aquamonitor+sprint

# Objectives
The overarching goal is to work towards running the Aquamonitor workflow on 
1. INCD compute, accessing data available at INCD
2. INCD compute, accessing data remotely on CREODIAS
Report on performance differences.

## Make the data available for the use case
- [ ] @jdries @MZICloudferro arrange access to CREODIAS object storage, ensure that cost can be reimbursed from CREODIAS VA allocation
- [ ] @jdries configure CREODIAS layer for INCD instance so that the OpenEO workflow can access the data remotely from INCD
- [x] @zbenta @tiagofglip raise issue on EODAG Github re download and unzip issue
- [x] @zbenta @tiagofglip @mariojmdavid provide object storage (swift/S3 interfaces), check integration with EGI Checkin.

## Progress on Notebook (MVP)
- [ ] @Jaapel Continue testing and improving Notebook using data for whole of Spain on Terrascope
- [ ] @Jaapel Switch to CREODIAS backend and test.
- [ ] @Jaapel Switch to INCD backend and test local data access performance.

cc @gena @Jaapel @gdonvito @mariojmdavid @jopina @jorge-lip

**Comment by backeb** [comment]
Yes!
________________________________

**Comment by sebastian-luna-valero** [comment]
Thanks!
