### ISSUE TITLE
Reproduce a simple EE script in C-Scale using OpenEO

### ISSUE THREAD

**Issue by gena** [c-scale-community/use-case-aquamonitor#3]
https://code.earthengine.google.com/d08354d7d4f0c1a1ec3178e5a4134feb

**Comment by sebastian-luna-valero** [comment]
Should this be closed?

**Comment by backeb** [comment]
Yes. This is done. See the aquamonitor notebook
________________________________

**Comment by sebastian-luna-valero** [comment]
Thanks!
