### ISSUE TITLE
Associate service account with VO to access information from all sites

### ISSUE THREAD

**Issue by backeb** [c-scale-community/use-case-aquamonitor#5]
One thing that we will need for the EGI cloud to work properly is to have a service account associated to the VO so we can have access to information from the sites without using a specific user identity. Let me dig the docs and send you some instructions

**Comment by sebastian-luna-valero** [comment]
I believe this can be closed?

**Comment by backeb** [comment]
I can't remember what this was about
________________________________

**Comment by sebastian-luna-valero** [comment]
Closing this then

@enolfc please re-open if necessary.
